# Generated by Django 4.2 on 2023-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerFruitsShop', '0002_product_movement_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_movement',
            name='created',
        ),
        migrations.AlterField(
            model_name='product_movement',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
