# Generated by Django 4.2 on 2023-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerFruitsShop', '0004_product_movement_f_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_movement',
            name='p_name',
            field=models.CharField(max_length=50),
        ),
    ]
