# Generated by Django 4.2 on 2023-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerFruitsShop', '0006_alter_product_movement_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_movement',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
